### ISSUE TITLE
Subject order

### ISSUE THREAD

**Issue by szechyjs** [square/certstrap#11]
When creating a CA the subject does not appear in the standard order.

I get the following

`C=US, O=Example Org, OU=Security, L=City Name, ST=State, CN=Example Org Root CA`

Typically its formatted like so

`C=US, ST=State, L=City Name, O=Example Org, OU=Security, CN=Example Org Root CA`

**Comment by sul3n3t** [comment]
Can you please reference a source or specification for your ordering?

**Comment by szechyjs** [comment]
Through some investigation it seems the problem is upstream in crypto/x509. 

https://github.com/golang/go/blob/master/src/crypto/x509/pkix/pkix.go#L130

**Comment by sul3n3t** [comment]
Thanks for digging deeper. It references RFC 5280. Appendix A.1 describes the RDNs are a SEQUENCE, rather than SET, so there is some order defined. It's pretty dense though.
