### ISSUE TITLE
Certstrap allows looser permissions but not stricter, which can lead to security issues

### ISSUE THREAD

**Issue by SBell6hf** [square/certstrap#136]
https://github.com/square/certstrap/blob/fda01dbea1db250eabfe77a8ceef55232cd5a515/depot/depot.go#L116
It must be a minor mistype, however this actually allows looser permissions and prohibits stricter ones, instead of the opposite that we want.

The corrent statement should be `if fi.Mode()&^tag.perm != 0 {`

**Comment by isemaya-square** [comment]
Fixed in https://github.com/square/certstrap/pull/141
