### ISSUE TITLE
Default permissions too open

### ISSUE THREAD

**Issue by SBell6hf** [square/certstrap#137]
https://github.com/square/certstrap/blob/fda01dbea1db250eabfe77a8ceef55232cd5a515/depot/pkix.go#L34
https://github.com/square/certstrap/blob/fda01dbea1db250eabfe77a8ceef55232cd5a515/depot/pkix.go#L35
`0440` and `0444` are much too open. Even `nobody` can read the certificate and key. It is insecure, and the problem is even worse with https://github.com/square/certstrap/issues/136.

**Comment by SBell6hf** [comment]
Other programs, like OpenSSH, would reject such a permission.
``` text
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@         WARNING: UNPROTECTED PRIVATE KEY FILE!          @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
Permissions 0444 for '/etc/ssh/ssh_host_rsa_key' are too open.
It is required that your private key files are NOT accessible by others.
This private key will be ignored.
Unable to load host key "/etc/ssh/ssh_host_rsa_key": bad permissions
Unable to load host key: /etc/ssh/ssh_host_rsa_key
sshd: no hostkeys available -- exiting.
```

**Comment by jdtw** [comment]
Doesn't the key get `0440`, not `0444`? https://github.com/square/certstrap/blob/fda01dbea1db250eabfe77a8ceef55232cd5a515/depot/pkix.go#L45

What's your concern with reading the certificate (`0444`)? That should be public and okay for anybody to read.

**Comment by isemaya-square** [comment]
Closing this - we fixed file permissions checking in https://github.com/square/certstrap/pull/141 so that the file permissions must match or be stricter than the permissions listed (440 or 444)
