### ISSUE TITLE
Get CA key error:  permission denied

### ISSUE THREAD

**Issue by kacpekwasny** [square/certstrap#144]
I am following the instructions step by step, I am on Windows 10:

```
$ git clone https://github.com/square/certstrap  
$ cd certstrap
$ go build 
$ ./certstrap.exe init --common-name CertAuth
$ ./certstrap.exe request-cert --common-name Alice
$ ./certstrap.exe sign Alice --CA CertAuth
Enter passphrase for CA key (empty for no passphrase): [all passwords are empty]
Get CA key error:  permission denied
```
I am on windows in powershell.
I also tried this fully on WSL debian but with following error:
`Get certificate request error: permission denied`

**Comment by kacpekwasny** [comment]
Did this on a VPS running debian and it worked.
I don't know if this is a reason to close this issue as it isn't really fixed.

**Comment by ekremparlak** [comment]
Same error happening to me on Debian 11.

**Comment by jdtw** [comment]
I can't repro on Mac OS master branch. What are the permissions for the key and CSR files?

**Comment by aperez456-nobody** [comment]
I think the issue has to do with the version of go you are using to build.
I tried to build project with go version 1.16.7, then 
I tried the precompiled binary and was able to resolve this. 
https://github.com/square/certstrap/releases/tag/v1.2.0

**Comment by isemaya-square** [comment]
I also built the project with go version 1.16.7, and used
https://github.com/square/certstrap/releases/tag/v1.2.0 and was able to sign.

**Comment by isemaya-square** [comment]
I was also able to built the project with go version 1.18.1 (latest version), and used
https://github.com/square/certstrap/releases/tag/v1.2.0 and was able to sign.

**Comment by isemaya-square** [comment]
Hi kacpekwasny. Thanks again for for flagging this. The issue should be fixed in https://github.com/square/certstrap/pull/155 - can you try cloning the latest version of certstrap in windows and running the steps again?
