### ISSUE TITLE
Get certificate request error: permission denied

### ISSUE THREAD

**Issue by snagrath-sys** [square/certstrap#149]
While signing the CSR using the following command:
./certstrap-master-linux-amd64 sign CSR_name --CA QA_RootCertAuth 

I am getting the following error: 
Get certificate request error: permission denied

Please guide how to fix this and sign the CSR.

Regards

**Comment by isemaya-square** [comment]
Hi @snagrath-sys. I believe we were able to fix this in https://github.com/square/certstrap/pull/155. Can you confirm?

**Comment by isemaya-square** [comment]
Closing because this should have been addressed in https://github.com/square/certstrap/pull/155

**Comment by snagrath-sys** [comment]
Hi,
Sorry for the late reply. Yes the issue was resolved.

Thanks,
Shriya
