### ISSUE TITLE
build github.com/square/certstrap: cannot load io/fs: malformed module path "io/fs": missing dot in first path element

### ISSUE THREAD

**Issue by AkashGuptaHC** [square/certstrap#150]
This is the issue I'm facing while doing the `go build` after `git clone` and `cd certstrap`

**Comment by AkashGuptaHC** [comment]
I got this working. Thanks!

**Comment by Dodain** [comment]
@AkashGuptaHC I am facing the same issue. How did you fix it ? 
build github.com/square/certstrap: cannot load io/fs: malformed module path "io/fs": missing dot in first path element

**Comment by Dodain** [comment]
Posting it if someone faces the issue in future.
io/fs came into go around 1.16 so if your go version is less than 1.16, that's likely the problem. You can check the version of go using "go version"
