### ISSUE TITLE
Unable to create ECDSA-based  (curve) CA using example from docs

### ISSUE THREAD

**Issue by inflatador** [square/certstrap#158]
Using the example from the readme:
`./certstrap init --common-name CertAuth --curve P-256`

Expected results: Create ECDSA-based CA

Actual results: certstrap outputs a help message which does **not** list `--curve `at all:

```
OPTIONS:
   --passphrase value                       Passphrase to encrypt private key PEM block
   --key-bits value                         Size (in bits) of RSA keypair to generate (example: 4096) (default: 4096)
   --expires value                          How long until the certificate expires (example: 1 year 2 days 3 months 4 hours) (default: "18 months")
   --organization value, -o value           Sets the Organization (O) field of the certificate
   --organizational-unit value, --ou value  Sets the Organizational Unit (OU) field of the certificate
   --country value, -c value                Sets the Country (C) field of the certificate
   --common-name value, --cn value          Sets the Common Name (CN) field of the certificate
   --province value, --st value             Sets the State/Province (ST) field of the certificate
   --locality value, -l value               Sets the Locality (L) field of the certificate
   --key value                              Path to private key PEM file (if blank, will generate new key pair)
   --stdout                                 Print certificate to stdout in addition to saving file
```

Version: `certstrap-1.2.0-darwin-amd64` on Mac OS X High Sierra , downloaded from Github shortly before filing this bug report.

**Comment by sestegra** [comment]
@inflatador The released version doesn't contain this feature.
https://github.com/square/certstrap/commit/95bea3d5881bd36de8cfff9393a04df35474dcac

Follow the [building procedure](https://github.com/square/certstrap#building) to build your own version.

**Comment by inflatador** [comment]
Thanks @sestegra  ! I've [requested a new release version](https://github.com/square/certstrap/issues/159) ; in the meantime I will follow your recommendation and build it myself.

Thanks again for your time!
