### ISSUE TITLE
Allow cert expiration times < 1 year

### ISSUE THREAD

**Issue by ontucker** [square/certstrap#21]
Would you accept a pull request that changes the cert generation interface from representing expiration as integer number of years to a time.Duration?  I would like to generate certs with shorter lifetimes.

**Comment by alokmenghrajani** [comment]
Please do! It should have been `time.Duration` from the get go.

Make sure to read https://github.com/square/certstrap/blob/master/CONTRIBUTING.md.

**Comment by alokmenghrajani** [comment]
`time.Duration` only supports Hours and smaller time units. Defining a day/month/year isn't hard but making sure things parse and pretty print nicely in the argument parser is going to be a pain.
