### ISSUE TITLE
Release a version

### ISSUE THREAD

**Issue by evenh** [square/certstrap#22]
Thanks for an awesome project! In order to have stability (and include a package in Homebrew), could you please consider releasing a version of certstrap, e.g. `v1.0.0` or `v0.0.1`?

**Comment by alokmenghrajani** [comment]
Sure. Would you be interested to tackle the few issues we have open and we could then wrap up a v1 release?

**Comment by evenh** [comment]
I've never coded a line of Go, but I'll sure give it a try :grinning:

**Comment by alokmenghrajani** [comment]
I think we can do a v1.0.0 release. Do you have a preference between git branches or git tags?

**Comment by evenh** [comment]
Great! I prefer tags as they are immutable.

**Comment by alokmenghrajani** [comment]
Done: https://github.com/square/certstrap/releases/tag/v1.0.0
