### ISSUE TITLE
Use of terminal.ReadPassword prevents windows compat

### ISSUE THREAD

**Issue by gmanfunky** [square/certstrap#3]
Use of the terminal package prevents certstrap from compiling on windows.

Would you mind not masking password entry or replacing it with something like the gopass package (https://github.com/howeyc/gopass)?

Depending on your goal, this may not be a great library. looks like it just quickly backspaces and overwrites with a space, which might still get logged by something you are trying to avoid.

**Comment by riyazdf** [comment]
I would prefer to continue masking password entry, but the gopass package looks like a good way to ensure windows compatibility.  

Give https://github.com/square/certstrap/pull/4 a look and see if that works for you.  Thanks for the feedback, and pull requests welcome :)

**Comment by gmanfunky** [comment]
#4 matches my local code perfectly. Unfortunately, it is a bit difficult to use the full godep flow on windows too.
