### ISSUE TITLE
How to create self signed certificate?

### ISSUE THREAD

**Issue by cpraveen412** [square/certstrap#32]
I'm trying to create a self signed certificate for cloud foundry consul server. could anyone help me?

Thanks

**Comment by mcpherrinm** [comment]
Certstrap doesn't have good support for self-signed certs.

You could try to use a CA (made with "certstrap init --cn host.example.com").  There may be some issues (in particular, we don't have a way to put Subject Alternate Names on CAs).

**Comment by cpraveen412** [comment]
sure i'll try that.

**Comment by cpraveen412** [comment]
Hi mcpherrinm,
It worked. could you help me in creating SSL Certs for cloud foundry HA_Proxy?

**Comment by cpraveen412** [comment]
I got it
