### ISSUE TITLE
Add cli parameter to enable extendedKeyUsage

### ISSUE THREAD

**Issue by dictvm** [square/certstrap#44]
I'm setting up a Consul cluster that requires rolling my own CA. That's how I found this awesome project. However, another requirement is the usage of `extendedKeyUsage` to enable client/server-authentication using the CA-signed certificates.

I've found references to `extKeyUsage` in the code but no way of configuring certstrap to actually create certificates with these parameters. It would be awesome if certstrap could support this.

**Comment by berndfischer63** [comment]
+1

**Comment by csstaub** [comment]
Default template already includes ext key usage for TLS client/server (https://github.com/square/certstrap/blob/master/pkix/cert_host.go#L42), is that sufficient for you or are you asking for a flag to have more flexibility?

**Comment by dictvm** [comment]
Oh, I see. I misunderstood the template. I've just added the CA, cert and key to my Consul cluster and its working perfectly fine. I don't have a need to opt-out of client/serverAuth via parameter.

**Comment by csstaub** [comment]
Sounds good, I will close this issue then. If you run into other issues let us know
