### ISSUE TITLE
Store files without spaces

### ISSUE THREAD

**Issue by sul3n3t** [square/certstrap#5]
Consider replaces spaces in output filenames with underscores. For example, instead of writing `out/Some\ Certificate\ Authority.crt`, write `out/Some_Certificate_Authority`.

**Comment by riyazdf** [comment]
Great idea, I've made a PR here: https://github.com/square/certstrap/pull/6

If/when this is merged, we'll probably want to update the instructions at https://github.com/square/keywhiz/wiki/Development-and-test-key-material
