### ISSUE TITLE
Publish docker image

### ISSUE THREAD

**Issue by MPV** [square/certstrap#66]
Hi, 
Would you be open to publishing an official docker image for `certstrap`?

Couldn't find any on Docker Hub:
https://hub.docker.com/search/?isAutomated=0&isOfficial=0&page=1&pullCount=0&q=certstrap&starCount=0

**Comment by csstaub** [comment]
We can definitely publish a Docker image for this, I might do this over the weekend. Do you have a specific use-case in mind?

**Comment by MPV** [comment]
For example for running in a CI environment where you don't necessarily can
or want to install the binary.
fre 30 nov. 2018 kl. 20:50 skrev Cedric Staub <notifications@github.com>:

**Comment by csstaub** [comment]
Just set this up on Docker Hub: https://hub.docker.com/r/squareup/certstrap/

Build is pending now.

**Comment by MPV** [comment]
@csstaub Works like a charm, thanks!
