### ISSUE TITLE
x509 API usage error

### ISSUE THREAD

**Issue by zenazn** [square/certstrap#7]
https://github.com/square/certstrap/blob/d84b22e1ca5af04d45c8745da95ceca7d792b87f/pkix/cert_auth.go#L62-L63

This is an error in the use of the `x509` API: `MaxPathLenZero` must be set to `true` if `MaxPathLen` is zero. http://godoc.org/crypto/x509#Certificate

(I'd submit a PR but don't think the CLA is worth the hassle for something so minor)

**Comment by riyazdf** [comment]
I put up a PR #9, though it seems like Go1.3 doesn't have the MaxPathLenZero field in its Certificate struct

**Comment by riyazdf** [comment]
We've updated the minimum to Go1.4 and fixed up the usage of the x509 API.  Thanks for finding this!
