### ISSUE TITLE
Must provide Common Name or domain

### ISSUE THREAD

**Issue by hantmac** [square/certstrap#89]
First,I use the next cmd:
```
git clone https://github.com/square/certstrap
$ cd certstrap
$ ./build
```
2.I got `certstrap-dev-25ea708a-darwin-amd64` in ./bin,and I exec:
```
./certstrap-dev-25ea708a-darwin-amd64 request-cert --ip 10.29.113.5
```
But, I got the error: **Must provide Common Name or domain**

**Comment by mcpherrinm** [comment]
You need to provide a Common Name for your certificate.

**Comment by hantmac** [comment]
> You need to provide a Common Name for your certificate.

I use the `request-cert` option, I also need use  `--common-name`? 
Just like `./certstrap-dev-25ea708a-darwin-amd64 request-cert --common-name XXX --ip 10.29.113.5` ?

**Comment by mcpherrinm** [comment]
Yes

**Comment by hantmac** [comment]
> Yes. If you provide a --domain it'll be used as the common name automatically, too.

Thanks a lot!
